------------------------------------------------------------------------------------------------------------------------------------
-- MotoX Corona Template
------------------------------------------------------------------------------------------------------------------------------------
-- Developed by Deep Blue Ideas.com [http:www.deepbueideas.com]
------------------------------------------------------------------------------------------------------------------------------------
--
-- SpriteSheetMotoX.lua
--
-- 23rd December 2018
-- Version 4.0
-- Requires Corona 2018.3326
------------------------------------------------------------------------------------------------------------------------------------

-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:7db4c3da7382353ab9841bc388644e58$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "Finish.png",
				spriteColorRect = { x = 0, y = 0, width = 194, height = 98 },
				textureRect = { x = 264, y = 637, width = 194, height = 98 },
				spriteSourceSize = { width = 194, height = 98 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "bg_indoorspurple.png",
				spriteColorRect = { x = 0, y = 0, width = 482, height = 322 },
				textureRect = { x = 3, y = 3, width = 482, height = 322 },
				spriteSourceSize = { width = 482, height = 322 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "btn_completed_iphone.png",
				spriteColorRect = { x = 0, y = 0, width = 336, height = 162 },
				textureRect = { x = 3, y = 328, width = 336, height = 162 },
				spriteSourceSize = { width = 336, height = 162 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "btn_left.png",
				spriteColorRect = { x = 0, y = 0, width = 67, height = 66 },
				textureRect = { x = 277, y = 882, width = 67, height = 66 },
				spriteSourceSize = { width = 67, height = 66 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "btn_restart.png",
				spriteColorRect = { x = 0, y = 0, width = 258, height = 162 },
				textureRect = { x = 3, y = 493, width = 258, height = 162 },
				spriteSourceSize = { width = 258, height = 162 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "btn_right.png",
				spriteColorRect = { x = 0, y = 0, width = 67, height = 66 },
				textureRect = { x = 277, y = 813, width = 67, height = 66 },
				spriteSourceSize = { width = 67, height = 66 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "obj_bike001.png",
				spriteColorRect = { x = 0, y = 28, width = 82, height = 54 },
				textureRect = { x = 173, y = 926, width = 82, height = 54 },
				spriteSourceSize = { width = 82, height = 82 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "obj_bikedown_001-1.png",
				spriteColorRect = { x = 0, y = 10, width = 82, height = 72 },
				textureRect = { x = 277, y = 738, width = 82, height = 72 },
				spriteSourceSize = { width = 82, height = 82 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "obj_bikefinish_001.png",
				spriteColorRect = { x = 0, y = 4, width = 82, height = 78 },
				textureRect = { x = 173, y = 770, width = 82, height = 78 },
				spriteSourceSize = { width = 82, height = 82 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "obj_bikefinish_002.png",
				spriteColorRect = { x = 0, y = 2, width = 82, height = 80 },
				textureRect = { x = 88, y = 826, width = 82, height = 80 },
				spriteSourceSize = { width = 82, height = 82 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "obj_bikefinish_003.png",
				spriteColorRect = { x = 0, y = 2, width = 82, height = 80 },
				textureRect = { x = 88, y = 743, width = 82, height = 80 },
				spriteSourceSize = { width = 82, height = 82 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "obj_bikefinish_004.png",
				spriteColorRect = { x = 0, y = 0, width = 82, height = 82 },
				textureRect = { x = 88, y = 658, width = 82, height = 82 },
				spriteSourceSize = { width = 82, height = 82 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "obj_bikehigh_001.png",
				spriteColorRect = { x = 0, y = 2, width = 82, height = 80 },
				textureRect = { x = 173, y = 687, width = 82, height = 80 },
				spriteSourceSize = { width = 82, height = 82 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "obj_bikeidle_001.png",
				spriteColorRect = { x = 0, y = 10, width = 82, height = 72 },
				textureRect = { x = 173, y = 851, width = 82, height = 72 },
				spriteSourceSize = { width = 82, height = 82 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "obj_bikeidle_002.png",
				spriteColorRect = { x = 0, y = 10, width = 82, height = 72 },
				textureRect = { x = 88, y = 909, width = 82, height = 72 },
				spriteSourceSize = { width = 82, height = 82 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "obj_bikeidle_003.png",
				spriteColorRect = { x = 0, y = 12, width = 82, height = 70 },
				textureRect = { x = 362, y = 811, width = 82, height = 70 },
				spriteSourceSize = { width = 82, height = 82 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "obj_bikeidle_004.png",
				spriteColorRect = { x = 0, y = 12, width = 82, height = 70 },
				textureRect = { x = 362, y = 738, width = 82, height = 70 },
				spriteSourceSize = { width = 82, height = 82 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "obj_biker001.png",
				spriteColorRect = { x = 0, y = 0, width = 38, height = 72 },
				textureRect = { x = 443, y = 451, width = 38, height = 72 },
				spriteSourceSize = { width = 38, height = 72 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "obj_bikeup_001.png",
				spriteColorRect = { x = 0, y = 8, width = 82, height = 74 },
				textureRect = { x = 3, y = 658, width = 82, height = 74 },
				spriteSourceSize = { width = 82, height = 82 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "obj_block001.png",
				spriteColorRect = { x = 0, y = 0, width = 74, height = 26 },
				textureRect = { x = 200, y = 983, width = 74, height = 26 },
				spriteSourceSize = { width = 74, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "obj_block002.png",
				spriteColorRect = { x = 0, y = 0, width = 98, height = 26 },
				textureRect = { x = 342, y = 480, width = 98, height = 26 },
				spriteSourceSize = { width = 98, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "obj_block003.png",
				spriteColorRect = { x = 0, y = 0, width = 98, height = 26 },
				textureRect = { x = 342, y = 451, width = 98, height = 26 },
				spriteSourceSize = { width = 98, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "obj_block004.png",
				spriteColorRect = { x = 0, y = 0, width = 194, height = 26 },
				textureRect = { x = 3, y = 985, width = 194, height = 26 },
				spriteSourceSize = { width = 194, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "obj_block005.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 98 },
				textureRect = { x = 461, y = 637, width = 26, height = 98 },
				spriteSourceSize = { width = 26, height = 98 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "obj_blockfinish001.png",
				spriteColorRect = { x = 0, y = 0, width = 74, height = 26 },
				textureRect = { x = 264, y = 493, width = 74, height = 26 },
				spriteSourceSize = { width = 74, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "obj_blockjoiner001.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 26 },
				textureRect = { x = 200, y = 658, width = 26, height = 26 },
				spriteSourceSize = { width = 26, height = 26 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "obj_paralax001.png",
				spriteColorRect = { x = 0, y = 0, width = 153, height = 120 },
				textureRect = { x = 342, y = 328, width = 153, height = 120 },
				spriteSourceSize = { width = 153, height = 120 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "obj_paralax002.png",
				spriteColorRect = { x = 0, y = 0, width = 237, height = 108 },
				textureRect = { x = 264, y = 526, width = 237, height = 108 },
				spriteSourceSize = { width = 237, height = 108 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "obj_paralax003.png",
				spriteColorRect = { x = 0, y = 0, width = 82, height = 244 },
				textureRect = { x = 3, y = 738, width = 82, height = 244 },
				spriteSourceSize = { width = 82, height = 244 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

